#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

USE_PROCD=1
START=22

start_service() {
        logger -t goheishamon "Starting service"
        [ -e /etc/config/goheishamon.toml ] || return 1
        procd_open_instance

        procd_set_param command sh -c "/usr/bin/goheishamon | logger -t goheishamon"
        procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-10} ${respawn_retry:-40}
        procd_set_param file /etc/config/goheishamon.toml

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}
